#!/usr/bin/env bash

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid; do
  # run when pushing a new branch
  if [[ "$remote_oid" = "$zero" ]]; then
    ./.git/hooks/pre-push-docs-branch
    exit $?
  fi
done

exit 0
